### ISSUE TITLE
Intelbras AMT - Alarm Control Panel Exemple

### ISSUE THREAD

**Issue by dougiteixeira** [dougiteixeira/generic-things#1]
https://github.com/dougiteixeira/generic-things/assets/31328123/f662b74a-0bb1-4c04-978a-0263a99d03ef

https://github.com/dougiteixeira/generic-things/assets/31328123/bb615e16-20d4-4fbd-b857-bd1000f7082a

Code:
```
alarm_control_panel:
  - platform: template
    panels:
      central_intelbras_amt:
        name: Central Alarme AMT
        unique_id: central_intelbras_amt_geral_001
        code_arm_required: false
        code_format: no_code
        value_template: >
            {% if is_state('binary_sensor.central_amt_disparada', 'on') -%}
                triggered
            {% elif is_state('binary_sensor.central_amt_ativada', 'off') -%}
                armed_home
            {%- else -%}
                disarmed
            {%- endif %}
        arm_home:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_ativar
        disarm:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_desativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_ativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_desativar
              
  - platform: template
    panels:
      central_intelbras_amt_particao_a:
        name: Central Alarme AMT - Partição A
        unique_id: central_intelbras_amt_geral_001A
        code_arm_required: false
        code_format: no_code
        value_template: >
            {% if is_state('binary_sensor.central_amt_particao_a', 'off') and is_state('binary_sensor.central_amt_disparada', 'on') -%}
                triggered
            {% elif is_state('binary_sensor.central_amt_particao_a', 'off') -%}
                armed_home
            {%- else -%}
                disarmed
            {%- endif %}
        arm_home:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_a_ativar
        disarm:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_a_desativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_a_ativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_a_desativar
              
  - platform: template
    panels:
      central_intelbras_amt_particao_b:
        name: Central Alarme AMT - Partição B
        unique_id: central_intelbras_amt_geral_001B
        code_arm_required: false
        code_format: no_code
        value_template: >
            {% if is_state('binary_sensor.central_amt_particao_b', 'off') and is_state('binary_sensor.central_amt_disparada', 'on') -%}
                triggered
            {% elif is_state('binary_sensor.central_amt_particao_b', 'off') -%}
                armed_home
            {%- else -%}
                disarmed
            {%- endif %}
        arm_home:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_b_ativar
        disarm:
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_b_desativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_b_ativar
          - service: button.press
            data: {}
            target:
              entity_id: button.central_amt_particao_b_desativar
```
